image:
  repository: ghcr.io/blinklabs-io/dingo
  tag: "0.73.4"
  pullPolicy: IfNotPresent

mithril:
  enabled: true
  cleanupAfterLoad: true
  verifyCertificates: true

environment:
  CARDANO_NETWORK: "preview"
  CARDANO_DATABASE_PATH: "/data"
  DINGO_STORAGE_MODE: "api"
  DINGO_PLUGINS_API_UTXORPC_CONFIG_PORT: "9090"
  DINGO_PLUGINS_API_BLOCKFROST_CONFIG_PORT: "3000"
  DINGO_PLUGINS_API_MESH_CONFIG_PORT: "8080"
  DINGO_PLUGINS_STORAGE_METADATA_PROVIDER: "sqlite"
  DINGO_PLUGINS_STORAGE_BLOB_PROVIDER: "badger"
  DINGO_DATABASE_WORKERS: "16"
  DINGO_DATABASE_QUEUE_SIZE: "500"
  DINGO_BACKFILL_BATCH_SIZE: "1000"

persistence:
  accessMode: ReadWriteOnce
  size: 60Gi

extraPodLabels:
  dingo.blinklabs.io/blockfrost-explorer: "true"

service:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    private: 3002
    relay: 3001
    metrics: 12798
    utxorpc: 9090
    blockfrost: 3000
    mesh: 8080

resources:
  requests:
    cpu: 1
    memory: 4Gi
  limits:
    cpu: 4
    memory: 12Gi
