image:
  repository: ghcr.io/blinklabs-io/dingo
  tag: "0.73.4"
  pullPolicy: IfNotPresent

mithril:
  enabled: true
  cleanupAfterLoad: true
  verifyCertificates: true

environment:
  CARDANO_NETWORK: "preview"
  CARDANO_DATABASE_PATH: "/data"
  DINGO_STORAGE_MODE: "api"
  DINGO_PLUGINS_API_UTXORPC_CONFIG_PORT: "9090"
  DINGO_PLUGINS_API_BLOCKFROST_CONFIG_PORT: "0"
  DINGO_PLUGINS_API_MESH_CONFIG_PORT: "0"
  DINGO_PLUGINS_STORAGE_METADATA_PROVIDER: "sqlite"
  DINGO_PLUGINS_STORAGE_BLOB_PROVIDER: "badger"

persistence:
  accessMode: ReadWriteOnce
  size: 60Gi

service:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    private: 3002
    relay: 3001
    metrics: 12798
    utxorpc: 9090
    blockfrost: 0
    mesh: 0

resources:
  requests:
    cpu: 1
    memory: 4Gi
  limits:
    cpu: 4
    memory: 12Gi
