#!/usr/bin/env sh
set -eu

DINGO_BIN="${DINGO_BIN:-dingo}"

export CARDANO_NETWORK="${CARDANO_NETWORK:-preview}"
export DINGO_STORAGE_MODE="${DINGO_STORAGE_MODE:-api}"
# Prefer the canonical plugin env vars, falling back to the pre-refactor
# names (DINGO_BLOCKFROST_PORT / DINGO_UTXORPC_PORT / DINGO_MESH_PORT) so an
# existing legacy port override keeps working.
export DINGO_PLUGINS_API_BLOCKFROST_CONFIG_PORT="${DINGO_PLUGINS_API_BLOCKFROST_CONFIG_PORT:-${DINGO_BLOCKFROST_PORT:-3000}}"
export DINGO_PLUGINS_API_UTXORPC_CONFIG_PORT="${DINGO_PLUGINS_API_UTXORPC_CONFIG_PORT:-${DINGO_UTXORPC_PORT:-9090}}"
export DINGO_PLUGINS_API_MESH_CONFIG_PORT="${DINGO_PLUGINS_API_MESH_CONFIG_PORT:-${DINGO_MESH_PORT:-8080}}"
export DINGO_PLUGINS_STORAGE_METADATA_PROVIDER="${DINGO_PLUGINS_STORAGE_METADATA_PROVIDER:-sqlite}"
export DINGO_PLUGINS_STORAGE_BLOB_PROVIDER="${DINGO_PLUGINS_STORAGE_BLOB_PROVIDER:-badger}"

exec "$DINGO_BIN" serve "$@"
