#!/usr/bin/env bash
set -euo pipefail

DATABASE_URL="${DATABASE_URL:?DATABASE_URL must point to the Dingo metadata Postgres database}"
DINGO_BIN="${DINGO_BIN:-dingo}"
NETWORK="${NETWORK:-preview}"
DATA_DIR="${CARDANO_DATABASE_PATH:-${PWD}/.dingo-preview}"

export CARDANO_DATABASE_PATH="${DATA_DIR}"
export DINGO_STORAGE_MODE="${DINGO_STORAGE_MODE:-api}"
export DINGO_PLUGINS_STORAGE_METADATA_PROVIDER="${DINGO_PLUGINS_STORAGE_METADATA_PROVIDER:-postgres}"
export DINGO_PLUGINS_STORAGE_METADATA_CONFIG_DSN="${DINGO_PLUGINS_STORAGE_METADATA_CONFIG_DSN:-${DATABASE_URL}}"
export DINGO_PLUGINS_STORAGE_BLOB_PROVIDER="${DINGO_PLUGINS_STORAGE_BLOB_PROVIDER:-badger}"
export DINGO_PLUGINS_API_BLOCKFROST_CONFIG_PORT="${DINGO_PLUGINS_API_BLOCKFROST_CONFIG_PORT:-0}"
export DINGO_PLUGINS_API_MESH_CONFIG_PORT="${DINGO_PLUGINS_API_MESH_CONFIG_PORT:-0}"
export DINGO_PLUGINS_API_UTXORPC_CONFIG_PORT="${DINGO_PLUGINS_API_UTXORPC_CONFIG_PORT:-0}"

exec "${DINGO_BIN}" -n "${NETWORK}" mithril sync
